services:
  db:
    image: postgres:16-alpine
    container_name: jobboard_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: jobboard
    ports:
      - "5432:5432"
    volumes:
      - jobboard_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d jobboard"]
      interval: 5s
      timeout: 5s
      retries: 20

volumes:
  jobboard_postgres_data:
